### ISSUE TITLE
MPI installation Issue and Solution

### ISSUE THREAD

**Issue by sachdevkartik** [diambra/DIAMBRAenvironment#3]
When pip installing packages from diambraPipRequirements.txt. I faced the following error:

>       _configtest.c:2:10: fatal error: mpi.h: No such file or directory
>        #include <mpi.h>
>                 ^~~~~~~
>       compilation terminated.
>       failure.
>       removing: _configtest.c _configtest.o
>       error: Cannot compile MPI programs. Check your configuration!!!
>       ----------------------------------------
>       ERROR: Failed building wheel for mpi4py

**Solution**

Paste following code in bash
 _brew install mpich_ (may work with or without)
  _sudo apt install libopenmpi-dev_
 _pip install https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz_

**Comment by diambra** [comment]
Thank you @sachdevkartik for devising a solution. In the README there is already the indication that, in order to use Stable Baselines (so to install the python requirements needed) you have to install `libopenmpi-dev` but maybe it is not clear enough.

As already said for issue #4, soon we will release an update with the smooth installation command using pip.

**Comment by sachdevkartik** [comment]
Nice that you @diambra already had mentioned in the README but i found it difficult to figure out. So, had to spend a couple of minutes to find a way.

**Comment by diambra** [comment]
Thank you again. We will make installation more and more straightforward.
